# Exploring UK petitions

Setup the environment and load in appropriate libraries

```{r  message=FALSE}
library(dplyr)
```

Load the data and tidy up columns

```{r message=FALSE}
df = read.csv("../data/all_the_petitions.csv", na.strings = c("", "NA"))

cleanDate = function(dateString) {
  strptime(dateString, "%Y-%m-%dT%H:%M:%S") %>% as.POSIXct
}

df$createdAt = cleanDate(df$createdAt)
df$updatedAt = cleanDate(df$updatedAt)
df$openAt = cleanDate(df$openAt)
df$closedAt = cleanDate(df$closedAt)
df$governmentResponseAt = cleanDate(df$governmentResponseAt)
df$scheduledDebateDate = cleanDate(df$scheduledDebateDate)
df$responseThresholdReachedAt = cleanDate(df$responseThresholdReachedAt)

df %>% select(action, createdAt, state, signatureCount) %>% head()
```

## How many are not closed yet?

```{r message=FALSE}
df %>% filter(!is.na(closedAt)) %>% count()
```

## How many petitions got a government response?

```{r message=FALSE}
governmentResponse = df %>% filter(!is.na(governmentResponseAt))
governmentResponse %>% count()
```

## What were they?

```{r message=FALSE}
governmentResponse %>% select(link, action, createdAt, state, signatureCount) %>% head()
```

## What have been the most popular petitions ever?

```{r message=FALSE}
df %>% arrange(desc(signatureCount)) %>% select(link, action, createdAt, state, signatureCount) %>% head()
```

Time for a bit of text processing based on this article - https://rstudio-pubs-static.s3.amazonaws.com/31867_8236987cf0a8444e962ccd2aec46d9c3.html#explore-your-data

```{r message=FALSE}
 Needed <- c("tm", "SnowballCC", "RColorBrewer", "ggplot2", "wordcloud", "biclust", "cluster", "igraph", "fpc") 
# Uncomment these lines to install the packages
 
#install.packages(Needed, dependencies=TRUE)   
   
# install.packages("Rcampdf", repos = "http://datacube.wu.ac.at/", type = "source")
```
 
```{r message=FALSE}
library(tm)

ds = DataframeSource(df %>% select(action))
docs = VCorpus(ds)
dtm = DocumentTermMatrix(docs)   
tdm = TermDocumentMatrix(docs)   
 
dtms <- removeSparseTerms(dtm, 0.1) # This makes a matrix that is 10% empty space, maximum.   
inspect(dtms)  

freq <- colSums(as.matrix(dtm))   
ord <- order(freq)   
```
 
## Most commonly used words in petitions
 
```{r message = FALSE}
 freq[tail(ord)]   
```


```{r message = FALSE}
library(wordcloud)

set.seed(142)   
wordcloud(names(freq), freq, min.freq=25)   

set.seed(142)   
wordcloud(names(freq), freq, max.words=100)  

set.seed(142)   
wordcloud(names(freq), freq, min.freq=20, scale=c(5, .1), colors=brewer.pal(6, "Dark2"))   
```